# Dependencies
markdown:         redcarpet
highlighter: pygments
plugins: [jekyll-paginate]
# Permalinks
permalink:        pretty

# Setup
title:            Kairene
tagline:          'A constructed language'
description:      "A easy-to-learn constructed language that is intuitively understood by AI in Kimeiga's games. Created by <a href='http://kimei.ga' target='_blank'>Kimeiga</a>."
# url:              https://kimeiga.github.io/kairen

url: https://kimeiga.github.io/
baseurl: /kairen
root: /kairen

author:
  name:           'Hakan Kimeiga Alpay'
  url:            http://kimei.ga

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kimeiga/kairen